package com.example.wavelength

object PromptLeftObject {
    val promptLeftList = listOf(
        "OLD SONG",
        "BAD CLASS",
        "USELESS TECH",
        "CHEAP",
        "UNNECESSARY HABIT",
        "PATHETIC SUPERHERO",
        "BAD SUPERPOWER",
        "USELESS INVENTION",
        "BAD PET",
        "TRASHY",
        "UNDERRATED GAME",
        "UNDERRATED MOVIE",
        "UNDERRATED SINGER",
        "UNDERRATED ACTOR",
        "UNDERRATED SONG",
        "HOT",
        "BAD HABIT",
        "UNFORGIVABLE",
        "DANGEROUS JOB",
        "ACTION MOVIE",
        "CAN'T AFFORD TO LOSE",
        "BAD PIZZA TOPPING",
        "HARD TO DO",
        "REQUIRES LUCK",
        "WASTE OF TIME",
        "MAINSTREAM",
        "QUIET PLACE",
        "YUCKY",
        "BORING HOBBY",
        "DARK",
        "DRY",
        "LOW CALORIE",
        "WORST LETTER",
        "FANTASY",
        "TALENT",
        "UNPOPULAR SPORT",
        "WEAK",
        "SOFT",
        "SMELLS BAD",
        "ROUGH",
        "GUILTY PLEASURE",
        "ROUND",
        "HARD TO FIND",
        "BAD PERSON",
        "NOT A SANDWICH",
        "BAD ADVICE",
        "BETTER HOT",
        "USELESS BODY PART",
        "YOU COULD BEAT UP",
        "USELESS MAJOR",
        "FRAGILE",
        "DIRTY",
        "FLAVORLESS",
        "SCARY ANIMAL",
        "BAD TV SHOW",
        "NEED",
        "TEMPORARY",
        "BAD ICE CREAM FLAVOR",
        "BAD FAST FOOD CHAIN",
        "VILLAIN",
        "WORST CHORE",
        "MILDLY ADDICTIVE",
        "NOT EMBARRASSING",
        "SMASH",
        "BORING TOPIC",
        "MESSY FOOD",
        "SPORT",
        "HARD TO SPELL",
        "UNTALENTED",
        "UNCONTROVERSIAL TOPIC",
        "DANGEROUS",
        "DIFFICULT TO USE",
        "UGLY WORD",
        "REPLACEABLE",
        "IMMATURE PERSON",
        "DISGUSTING CEREAL",
        "HAPPENS SLOWLY",
        "UNREASONABLE PHOBIA",
        "RARE",
        "USELESS IN EMERGENCY",
        "WEIRD GREETING",
        "WORTHLESS",
        "BAD ACTOR",
        "APPETIZER",
        "BAD INFLUENCE",
        "DOG NAME"
    )
}