package com.example.wavelength

object PromptRightObject {
    val promptRightList = listOf(
        "NEW SONG",
        "GOOD CLASS",
        "USEFUL TECH",
        "EXPENSIVE",
        "NECESSARY HABIT",
        "IMPRESSIVE SUPERHERO",
        "GOOD SUPERPOWER",
        "USEFUL INVENTION",
        "GOOD PET",
        "CLASSY",
        "OVERRATED GAME",
        "OVERRATED MOVIE",
        "OVERRATED SINGER",
        "OVERRATED ACTOR",
        "OVERRATED SONG",
        "COLD",
        "GOOD HABIT",
        "FORGIVABLE",
        "SAFE JOB",
        "ADVENTURE MOVIE",
        "WANT TO LOSE",
        "GOOD PIZZA TOPPING",
        "EASY TO DO",
        "REQUIRES SKILL",
        "GOOD USE OF TIME",
        "NICHE",
        "LOUD PLACE",
        "YUMMY",
        "INTERESTING HOBBY",
        "LIGHT",
        "WET",
        "HIGH CALORIE",
        "BEST LETTER",
        "SCI-FI",
        "SKILL",
        "POPULAR SPORT",
        "STRONG",
        "HARD",
        "SMELLS GOOD",
        "SMOOTH",
        "OPENLY LOVE",
        "POINTY",
        "EASY TO FIND",
        "GOOD PERSON",
        "SANDWICH",
        "GOOD ADVICE",
        "BETTER COLD",
        "USEFUL BODY PART",
        "WHO'D BEAT YOU UP",
        "USEFUL MAJOR",
        "DURABLE",
        "CLEAN",
        "FLAVORFUL",
        "CUTE ANIMAL",
        "GOOD TV SHOW",
        "WANT",
        "PERMANENT",
        "GOOD ICE CREAM FLAVOR",
        "GOOD FAST FOOD CHAIN",
        "HERO",
        "BEST CHORE",
        "HIGHLY ADDICTIVE",
        "VERY EMBARRASSING",
        "PASS",
        "FASCINATING TOPIC",
        "CLEAN FOOD",
        "GAME",
        "EASY TO SPELL",
        "TALENTED",
        "CONTROVERSIAL TOPIC",
        "SAFE",
        "EASY TO USE",
        "BEAUTIFUL WORD",
        "IRREPLACEABLE",
        "MATURE PERSON",
        "DELICIOUS CEREAL",
        "HAPPENS QUICKLY",
        "REASONABLE PHOBIA",
        "COMMON",
        "USEFUL IN EMERGENCY",
        "NORMAL GREETING",
        "PRICELESS",
        "GOOD ACTOR",
        "MEAL",
        "GOOD INFLUENCE",
        "CAT NAME"
    )
}